[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow2 = "76bwsGyECyqNWDaQ85Jn9TLqiSEW7D8JpgzzKJft7t3N"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/karlwayneantoine/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
