[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vault = "B6yKmDcGT47RM9i6hYHZ6gL6jsysQKv1qxLc3ZsCA3BW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/karlwayneantoine/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
